# Docker Compose file version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
    #add other environment variables specific to the backend here
      - DB_URL=jdbc:postgresql://database:5432/vilagszepdatabase
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - SECRET_KEY=3FBbB41C62GCFgaD*gc5G3c1Fec3-CCD

    #!if you already have a database use this with your configuration intead of the one on above
    #environment:
    # - DB_URL=jdbc:postgresql://roundhouse.proxy.rlwy.net:37357/railway
    # - DB_USERNAME=postgres
    # - DB_PASSWORD=3FBbB41C62GCFgaD*gc5G3c1Fec3-CCD
    # - SECRET_KEY=3FBbB41C62GCFgaD*gc5G3c1Fec3-CCD



  database:
    image: postgres
    environment:
      POSTGRES_DB: vilagszepdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5555:5432
